name: Deploy to Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Send request to Nginx
      run: curl https://coil.cs.bgu.ac.il/activate_script
