name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure all history is fetched to access branches and tags
          
      - name: List directory contents again
        run: ls -R 

      - name: List directory contents short
        run: ls 

      - name: List directory contents shorter
        run: ls ./Backend
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./Backend/src

      - name: Run tests
        run: npm test
        env:
          NODE_ENV: test
        working-directory: ./Backend/src
